# Generated by Django 4.2.26 on 2025-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_category', models.CharField(blank=True, max_length=255)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('pathway', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, max_length=255)),
                ('block', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
                ('video_code', models.CharField(blank=True, max_length=255)),
                ('video_title', models.CharField(max_length=255)),
                ('main_camera_man', models.CharField(blank=True, max_length=255)),
                ('camera_assistant', models.CharField(blank=True, max_length=255)),
                ('instructor_on_camera', models.CharField(blank=True, max_length=255)),
                ('graphic_designer', models.CharField(blank=True, max_length=255)),
                ('script_link', models.URLField(blank=True)),
                ('screencast_link', models.URLField(blank=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
